### ISSUE TITLE
Collector issue

### ISSUE THREAD

**Issue by BDT-4248** [GhexterCortes/eris-collectors#1]
i keep getting this error whenever i try out the collector thing. What can i do to fix it?
Error message: 
`throw new Error("getOriginalMessage cannot be used to acknowledge an interaction, please use acknowledge, createMessage, defer, deferUpdate, or editParent first.");
Error: getOriginalMessage cannot be used to acknowledge an interaction, please use acknowledge, createMessage, defer, deferUpdate, or editParent first.`

**Comment by catplvsplus** [comment]
I updated the package and see if this issue has been fixed

**Note:** The update contains breaking changes

**Comment by BDT-4248** [comment]
It works but...

1. the collector never ends
2. for some reason within the `collector.on()`, it keeps showing the whole componentinteraction I've pressed in console log even though I haven't put that in the code. Yes I've checked to see if any event is causing this but they're either after `return;` (so it'll never reach the console log part) or it's in the comments so it wouldn't be read as code

**Comment by catplvsplus** [comment]
> It works but...
> 
> 1. the collector never ends
> 2. for some reason within the `collector.on()`, it keeps showing the whole componentinteraction I've pressed in console log even though I haven't put that in the code. Yes I've checked to see if any event is causing this but they're either after `return;` (so it'll never reach the console log part) or it's in the comments so it wouldn't be read as code

1. I assume you used `timer` instead of `time` when creating your collector. I changed that to match the discord.js style of collector.

2. I will need to see your code related to collector because I checked the coode and collectors doesn't call console.log.

**Comment by BDT-4248** [comment]
> 1. I assume you used `timer` instead of `time` when creating your collector. I changed that to match the discord.js style of collector.
> 2. I will need to see your code related to collector because I checked the coode and collectors doesn't call console.log.

1. uh no... but i'll try again since maybe my system did something idk
2. um sure
what i keep getting in console.log : `Collection(1) [Map] {
  '1090660553749434439' => ComponentInteraction {...}`
code: 
``const filter = int => [`yesban`,`noban`].includes(int.data.custom_id);``
`const collector = new InteractionCollector({`
 `  client: ctx,`
 `  channel: i.channel,`
 `  time: 10000,`        
 `  filter: filter`
`});`
`collector.on('collect', interaction => {});`
`collector.on('end', reason => console.log('reason')); `

**Comment by catplvsplus** [comment]
I cannot replicate your problem with any of the collectors as you can see in the image below.
![image](https://user-images.githubusercontent.com/69035887/228743949-b52b50db-b43f-412c-9047-c8472ca87e44.png)

*The test is from [Repo test folder](https://github.com/NotGhex/eris-collectors/tree/main/test)*

However, I have a conclusion that you're logging the collected interactions with the "end" event because I also changed the parameters for that event as seen in the [Collector type declaration](https://github.com/NotGhex/eris-collectors/blob/345a07c743de885142aaea2f31d29ffc01f904ef/src/classes/Collector.ts#L22)

![image](https://user-images.githubusercontent.com/69035887/228744843-56824b3e-a9c9-4b02-9802-4f51a23f21ca.png)

**Comment by BDT-4248** [comment]
Ok so i get this error now:
![Screenshot_181](https://user-images.githubusercontent.com/51002397/228760696-5cdc8fe0-6568-461f-ad45-41ced1b14040.png)

code:
![Screenshot_180](https://user-images.githubusercontent.com/51002397/228760794-a032ea7c-52f7-4bbd-b727-3b2adeae5e8f.png)

at this point I really think your package just hates me or something lmao

**Comment by catplvsplus** [comment]
> Ok so i get this error now: ![Screenshot_181](https://user-images.githubusercontent.com/51002397/228760696-5cdc8fe0-6568-461f-ad45-41ced1b14040.png)
> 
> code: ![Screenshot_180](https://user-images.githubusercontent.com/51002397/228760794-a032ea7c-52f7-4bbd-b727-3b2adeae5e8f.png)
> 
> at this point I really think your package just hates me or something lmao

I recommend reading [List of breaking changes](https://github.com/NotGhex/eris-collectors/blob/main/MovingToV2.md)

**Comment by BDT-4248** [comment]
ok i didn't realize that
but i've tested everything and all works well
thank you so much
