### ISSUE TITLE
Cannot start my bot

### ISSUE THREAD

**Issue by BDT-4248** [GhexterCortes/eris-collectors#2]
Ever since eris v0.18.0 came out and i downloaded that, this package started to crash my bot on startup

it's been driving me crazy and here's the error
![img114](https://github.com/user-attachments/assets/aaaa4198-d349-461c-875d-4a1cfdc7c7b8)

**Comment by BDT-4248** [comment]
i dont get the error as i downgraded to 0.17.2 again but it's highly disheartening that i have to stay in the old version of eris

**Comment by catplvsplus** [comment]
Package has been updated to support new eris version [eris-collectors@3.0.1](https://www.npmjs.com/package/eris-collectors). Report if any issues occur.
